name: Run Flask Unit Tests

on:
  push:
    branches: [ main, ci_cd_test_setup ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create config.toml from secrets
      run: |
        mkdir -p instance
        cat <<EOF > instance/config.toml
        ES_API_KEY_ID = "${{ secrets.ES_API_KEY_ID }}"
        ES_API_KEY_SECRET = "${{ secrets.ES_API_KEY_SECRET }}"
        ES_NODES = ${{
          secrets.ES_NODES
        }}
        SECRET_KEY = "${{ secrets.SECRET_KEY }}"
        META_SERVICE = "${{ secrets.META_SERVICE }}"
        EOF
    
    - name: Run tests
      run: |
        pytest app/test